-- bookings 테이블 생성 SQL
CREATE TABLE IF NOT EXISTS public.bookings (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamptz DEFAULT now() NOT NULL,
    use_date date NOT NULL,
    use_time text NOT NULL,
    participants integer NOT NULL,
    grade_class text NOT NULL,
    student_name text NOT NULL,
    phone_number text NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL
);

-- RLS(Row Level Security) 설정 (필요 시)
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;

-- 모든 사용자에게 조회 및 삽입 권한 부여 (실제 운영 시에는 더 엄격하게 설정 권장)
CREATE POLICY "Allow public insert" ON public.bookings FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public select" ON public.bookings FOR SELECT USING (true);
CREATE POLICY "Allow admin update" ON public.bookings FOR UPDATE USING (true);
CREATE POLICY "Allow admin delete" ON public.bookings FOR DELETE USING (true);
